[project]
name = "stress-detection"
version = "0.1.0"
description = "Stress Detection Frontend"
authors = [
    {name = "Harish", email = "gehloth03@gmail.com"},
]
requires-python = ">=3.10"

dependencies = [
    "streamlit"
]